import { RootProvider } from 'fumadocs-ui/provider/next';
import './global.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next'; 
import type { ReactNode } from 'react';
import Footer from '@/components/footer/Footer';

const inter = Inter({
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "My Docs",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"),
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        <RootProvider>
          {children}
        </RootProvider>

        {/* 3. ফুটার এখানে থাকলে সব পেজে লোড হবে। 
            তবে Footer.tsx-এর ভেতরের লজিক অনুযায়ী এটি /docs পেজে হাইড হয়ে যাবে। */}
        <Footer />
      </body>
    </html>
  );
}